### ISSUE TITLE
JellySocketApplication tests fail on Node v4

### ISSUE THREAD

**Issue by carstenschwede** [JoshuaWise/jellysocket#1]
`require('util').inherits(JellySocketApplication, EventEmitter);
`

seems to overwrite the previous prototype declaration in Node v4.
This results in the following tests failing

    $> node -v
    v4.3.1

    $> npm test
    [SNIP]
    JellySocketApplication
    1) should expose connected clients
    2) should expose server
    3) should lock and unlock properly
    4) should disconnect all clients and lock the app
    5) should broadcast to all clients
    6) should fire the "vacant" event when locked with no clients
    7) should fire the "vacant" after last client disconnects, if locked
    8) should mount to the specified path
    9) should respect verifyClient option
    10) should not send heartbeats when heartbeat option is 0
    11) should send ping heartbeats when heartbeat option is a positive number
    12) should send pong heartbeats when heartbeatForgiveness is 0
    13) should disconnect client when too many heartbeats are missed

Tests don't fail on Node 5.7.0.

**Comment by JoshuaWise** [comment]
Thanks for pointing this out. I've added node v4.3.1 to travis, to prevent this kind of mistake in the future.

Fixed in 400106fbed5c9178fbd02a2cb3337127fad27fd0. Published to v0.3.2.
